name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        ruby-version: [3.1, '3.0', 2.7, 2.6, 2.5, 2.4, 2.3, 2.2, jruby-9.1]
        experimental: [false]
        include:
          - ruby-version: head
            experimental: true
          - ruby-version: jruby-head
            experimental: true
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby-version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake
